@MovieApi_HostAddress = http://localhost:5053

POST {{MovieApi_HostAddress}}/api/seed

###

POST {{MovieApi_HostAddress}}/api/recommend
Content-Type: application/json

{
	"mood": "funny and clever"
}

###
